title: Enrico's Place # name of the site
author: Enrico # name of site's author
email: enrico.astoin@gmail.com # email of site's author
url: https://riggraz.dev # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  A (nearly) no-CSS, fast, minimalist Jekyll theme.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: null
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: false # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: compressed

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-spaceship
  # - jektex
# jektex:
#   cache_dir: ".jektex-cache"
#   ignore: ["*.xml"]
#   silent: false
#   macros:
#     - ["\\Q", "\\mathbb{Q}"]
#     - ["\\C", "\\mathbb{C}"]
